drop database hospitales;
create database hospitales;

DROP TABLE `hospitales`.`hospitales.doctores_consultorios`;
DROP TABLE `hospitales`.`hospitales.receta_paciente_doctores`;
DROP TABLE `hospitales`.`hospitales.doctores`;
DROP TABLE `hospitales`.`hospitales.consultorio`;
DROP TABLE `hospitales`.`hospitales.pacientes`;
DROP TABLE `hospitales`.`hospitales.especialidades`;
DROP TABLE `hospitales`.`hospitales.enfermeros`;
DROP TABLE `hospitales`.`hospitales.receta`;
DROP TABLE `hospitales`.`hospitales.areas`;
COMMIT;