SELECT * FROM HOSPITALES.AREAS AS AR
INNER JOIN HOSPITALES.ENFERMEROS AS ENF ON AR.FIIDAREA = ENF.FIIDAREA;



SELECT * FROM HOSPITALES.DOCTORES AS DOC
INNER JOIN HOSPITALES.ESPECIALIDADES AS ESP ON DOC.FIIDESPECIALIDAD = ESP.FIIDESPECIALIDAD;


SELECT * FROM hospitales.doctores AS DOC
INNER JOIN hospitales.doctores_consultorios AS DCC ON DOC.FIIDDOCTOR= DCC.FIIDDOCTOR
inner join hospitales.consultorio as CON on DCC.FIIDCONSULTORIO=CON.FIIDCONSULTORIO;



SELECT * FROM hospitales.pacientes as PA;

select * from hospitales.pacientes as PA
inner join hospitales.receta_paciente_doctores as RPD on PA.FIIDPACIENTE=RPD.FIIDPACIENTE
inner join hospitales.receta as REC on RPD.FIIDRECETA = REC.FIIDRECETA;


SELECT
-- *
CON.NUMERO_CONSULTORIO,
CON.NOMBRE_CONSULTORIO,
AR.NOMBRE_AREA,
AR.DESCRIPCION,
CASE AR.HABILITADO WHEN 0 THEN 'APAGADO' ELSE 'ENCENDIDO' END ESTATUS_AREA
FROM hospitales.consultorio AS CON
inner join hospitales.areas as AR on CON.FIIDAREA= AR.FIIDAREA
WHERE CON.NUMERO_CONSULTORIO=1
AND CON.FIIDAREA=1;